# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c54bfe9a2a4cb005049e4a3d0aea5cbff23ac2bd94b12aea455b6b875e98aa863ee0e584428cf707686c21b7e8fa9ab7afe408e92b8c38f730760a7865b1f7d0

test:
  secret_key_base: 21461879ccec16603e0d86750ac337638ffb71f944e14d69aeda6175d5524efa5d3ed18111dfe6439066a1001aca6fc4edb4c2741467174b34ec37702b610783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
